### ISSUE TITLE
Error with main.css on GH-Pages

### ISSUE THREAD

**Issue by Jorick** [Jorick/Kano-Kwai-Laarne#15]
The page build failed for the `main` branch with the following error:

Your SCSS file `assets/css/main.scss` has an error on line 3: File to import not found or unreadable: custom. Load paths: _sass assets/css /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.

For information on troubleshooting Jekyll see:

 https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=336525974&page_build_id=232760478

**Comment by PieterVanPoyer** [comment]
@Jorick yes der is ne Pull Request. Check it out.
